---
healthcheck:
  workingText: "WORKING"
mqttserver:
  host: "localhost"
  port: 1883
  user: "admin"
  pass: "admin"
  subscriptionRequests:
    - topic: 'chat/+/room/+'
      qos: 2
      plugins:
        - plugin: "persist_message"
          messagePattern: ".*"
    - topic: 'mqttbot/history/#'
      qos: 2
      plugins:
        - plugin: "send_history"
          messagePattern: "\"history\""
    - topic: 'mqttbot/register/#'
      qos: 2
      plugins:
        - plugin: "register_user"
          messagePattern: "register"
    - topic: 'mqttbot/acl/#'
      qos: 2
      plugins:
        - plugin: "add_user_subscription_acl"
          messagePattern: "aclpermitsubscription"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message":{"_ttl": { "enabled": true, "default": "2d" }}}}'
redis:
  host: "localhost"
  port: 6379
  password: ""
  maxPoolSize: 10
logger:
  level: "debug"
plugins:
  modulesPath: "../plugins/load_modules.lua"
  pluginsPath: "../plugins/"
